### ISSUE TITLE
Wiki - add images

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.Website.Menu.json#40]
Hi @bradystroud 
CC @tiagov8 @gregharrisssw @christianmorfordwaitessw 

I have added an image to the root folder
![](https://github.com/SSWConsulting/SSW.Website.Menu.json/blob/master/D612C5E5-6720-4302-AC24-4AC8EDA64EDC.png)

1. Please move it to an /images folder
2. Tell me how you created the folder
3. Rename that image to have a better name
4. On wiki add that image
5. On wiki add links to the places that the menu applies to
Eg. The SSW Website, SSW Rules, SSW People

-a
www.AdamCogan.com

**Comment by bradystroud** [comment]
cc: @tiagov8 @gregharrisssw @christianmorfordwaitessw @pierssinclairssw @AttackOnMorty
Hi @adamcogan,

> 1. Please move it to an /images folder
> 2. Tell me how you created the folder
> 3. Rename that image to have a better name

Done - As per our conversation, this is currently not possible on the GitHub Web UI.  
For more info, see https://github.community/t/how-to-rename-the-images-on-github/930/6
I cloned the repo and made the changes locally but next time I should follow the docs and use the GitHub CLI to make changes like this.


> 4. On wiki add that image
> 5. On wiki add links to the places that the menu applies to 
> Eg. The SSW Website, SSW Rules, SSW People

Done - https://github.com/SSWConsulting/SSW.Website.Menu.json/wiki/How-to-edit-the-SSW.Website.Menu%3F


-Brady
